name: Push to Replicate

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

          - name: Install Cog
      run: |
        curl -L https://storage.googleapis.com/replicate-cog/latest/cog-linux -o cog
        chmod +x cog
        sudo mv cog /usr/local/bin/cog

    - name: Login to Replicate
      run: |
        export COG_LOGIN_TOKEN="${{ secrets.REPLICATE_API_TOKEN }}"

    - name: Push model
      run: |
        cog push r8.im/elabercha-ui/oldfoto-restore


      - name: Push model
        run: |
          cog push r8.im/elabercha-ui/oldfoto-restore
